name: Deploy to staging environment

on:
  push:
    branches: [ stage ]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Gcloud Account
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT}}

      - name: Deploy to cloud run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
          service: ${{ secrets.GCP_SERVICE_NAME }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: europe-west1


