name: Deploy to staging environment

on:
  push:
    branches: [ stage, feature/integrate-typeorm-and-add-user-table ]

jobs:
  deploy:
    name: Build and deploy project
    runs-on: ubuntu-latest
    environment: Staging
    env:
      Container_BASE_URL: gcr.io
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:${{ github.sha }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Gcloud Account
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT}}

      - name: Configure Docker
        run: gcloud auth configure-docker $Container_BASE_URL

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:${{ github.sha }}
          push: true

      - name: Deploy docker image to cloud run
        run: gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} --image $IMAGE_NAME --quiet --platform managed --region ${{secrets.GCP_REGION}} --project ${{ secrets.GCP_PROJECT_ID }}



