name: Deploy to staging environment

on:
  push:
    branches: [ stage ]

jobs:
  deploy:
    name: Build and deploy project
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{secrets.GCP_REGION}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACTS_REPOSITORY }}/${{ secrets.GCP_APP_NAME }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Gcloud Account
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT}}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build container
        run: docker build . -t $IMAGE_NAME

      - name: Push docker image
        run: docker push $IMAGE_NAME

      - name: Deploy docker image to cloud run
        run: gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} --image $IMAGE_NAME --quiet --platform managed --region ${{secrets.GCP_REGION}} --project ${{ secrets.GCP_PROJECT_ID }}


